## YAML Template.
---
server:
    port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  api-docs:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    # healthcheck:
    #   enabled: true
    fetch-registry: true
spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
      - id: customer_service
        uri: http://customer:8081
        predicates:
        - Path=/customer/**