## YAML Template.
---
server:
    port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

springdoc:
  api-docs:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      
spring:
  application:
    name: apigetway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
      - id: customer_service
        uri: lb://customer
        predicates:
        - Path=/**